spring:
  application.name: spring-cloud-dynamic-gw
  cloud.gateway:
    discovery.locator.enabled: true
    routes:
        - id: micro-service1-route
          uri: http://localhost:10001
          predicates:
            - Path=/micro-service1/**
          filters:
            - StripPrefix=1

dynamic-routes:
  routes:
    - id: micro-service2-route
      uri: http://localhost:10002
      predicates:
        - Path=/micro-service2/**
      filters:
        - StripPrefix=1

management.endpoints.web.exposure.include: '*'

springdoc:
  swagger-ui.tagsSorter: alpha
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
